name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run:
          echo "Hello World!"
      - name: Show Date and Time
        run:
          date
      - name: List Files in Current Directory
        run:
            ls -l